// https://github.com/Justineo/vue-awesome
import Vue from 'vue'
import 'vue-awesome/icons/angle-left'
import 'vue-awesome/icons/angle-right'
import 'vue-awesome/icons/angle-down'
import 'vue-awesome/icons/angle-up'
import 'vue-awesome/icons/check'
import 'vue-awesome/icons/ban'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/heart'
import 'vue-awesome/icons/download'
import 'vue-awesome/icons/info-circle'
import 'vue-awesome/icons/circle-o-notch'
import 'vue-awesome/icons/plus'
import 'vue-awesome/icons/minus'