// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_CART = 'DELETE_CART'
export const SET_USAGE = 'SET_USAGE'
export const DELETE_USAGE = 'DELETE_USAGE'
export const VERIFY_PRODUCTS = 'VERIFY_PRODUCTS'
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT'

// Lightbox
export const ADD_TO_LIGHTBOX = 'ADD_TO_LIGHTBOX'
export const REMOVE_FROM_LIGHTBOX = 'REMOVE_FROM_LIGHTBOX'
export const DELETE_LIGHTBOX = 'DELETE_LIGHTBOX'
export const SET_LIGHTBOX = 'SET_LIGHTBOX'

// User
export const SET_USER = 'SET_USER'

// Product
export const SET_PRODUCT = 'SET_PRODUCT'

// MISC
export const CHANGE_TITLE = 'CHANGE_TITLE'