// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_CART = 'DELETE_CART'
export const SET_USAGE = 'SET_USAGE'
export const DELETE_USAGE = 'DELETE_USAGE'
export const VERIFY_PRODUCTS = 'VERIFY_PRODUCTS'
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT'

// Lightbox
export const ADD_TO_LIGHTBOX = 'ADD_TO_LIGHTBOX'
export const REMOVE_FROM_LIGHTBOX = 'REMOVE_FROM_LIGHTBOX'
export const RESET_LIGHTBOX = 'RESET_LIGHTBOX'
export const SET_LIGHTBOX = 'SET_LIGHTBOX'

// User
export const SET_USER = 'SET_USER'
export const SET_USER_DOWNLOAD_ACCESS = 'SET_USER_DOWNLOAD_ACCESS'

// Product
export const SET_PRODUCT = 'SET_PRODUCT'
export const SET_PRODUCT_LOADED = 'SET_PRODUCT_LOADED'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_RESULTS_LOADED = 'SET_SEARCH_RESULTS_LOADED'
export const SET_POST = 'SET_POST'
export const SET_POST_LOADED = 'SET_POST_LOADED'
export const SET_PRODUCT_TYPES = 'SET_PRODUCT_TYPES'
export const SET_PRODUCT_TYPES_LOADED = 'SET_PRODUCT_TYPES_LOADED'
export const SET_ATTACHMENT = 'SET_ATTACHMENT'
export const SET_ATTACHMENT_LOADED = 'SET_ATTACHMENT_LOADED'


// MISC
export const CHANGE_TITLE = 'CHANGE_TITLE'
